### ISSUE TITLE
[Bug]: Hybrid server Crash

### ISSUE THREAD

**Issue by ItzPear** [Virtuoel/Pehkui#283]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

Forge 36.2.26

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

Upon starting the server with a Hybrid server such as Arclight, Pehkui causes the server to crash at startup.

### Full list of installed mods

Macaw's bridges
Dynmap forge
Wolves with Armor
Architectury
Spartan Weaponry
Macaw's Fences and Gates
Carftable Horse Armor and Saddle
Small Ships
Path under Gates
Better Horse Armor
Spartan Shields

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

[30May2022 19:34:24.235] [main/INFO] [Arclight/]: 

       ___           ___     __   /\
      /   | ________/ (_)__ / /  / /
     / /| |/ __/ __/ / / _ / _ \/__/
    / ___ / / / /_/ / / / / // / /
   /_/  |/_/  \__/_/_/\_ /_//_/ /
                     /__/     \/

    Version arclight-1.16.5-1.0.24-SNAPSHOT-dabfea43
    Build Date 2022-05-28 05:53:22

[30May2022 19:34:24.325] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.26, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[30May2022 19:34:24.327] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_312 by Red Hat, Inc.
[30May2022 19:34:24.867] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[30May2022 19:34:24.922] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/opt/service/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[30May2022 19:34:26.675] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [io.izzel.arclight.impl.ArclightConnector_Forge]
[30May2022 19:34:26.738] [main/INFO] [Arclight/]: Arclight core mixin added.
[30May2022 19:34:26.742] [main/INFO] [Arclight/]: Arclight optimization mixin added.
[30May2022 19:34:26.754] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[30May2022 19:34:27.318] [main/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/color/ItemColors for invalid dist DEDICATED_SERVER
[30May2022 19:34:27.318] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/color/ItemColors (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/color/ItemColors for invalid dist DEDICATED_SERVER)
[30May2022 19:34:27.321] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.color.ItemColors was not found wolveswitharmor.mixins.json:ItemColorsMixin
[30May2022 19:34:28.052] [main/WARN] [mixin/]: Error loading class: net/minecraft/block/entity/LecternBlockEntity$1 (java.lang.ClassNotFoundException: null)
[30May2022 19:34:28.053] [main/WARN] [mixin/]: @Mixin target net.minecraft.block.entity.LecternBlockEntity$1 was not found pehkui.mixins.json:reach.LecternBlockEntityMixin
[30May2022 19:34:28.373] [main/WARN] [mixin/]: Error loading class: top/theillusivec4/culinaryconstruct/common/item/CulinaryItemBase (java.lang.ClassNotFoundException: null)
[30May2022 19:34:28.374] [main/WARN] [mixin/]: @Mixin target top.theillusivec4.culinaryconstruct.common.item.CulinaryItemBase was not found origins.forge.mixins.json:compat.cconstruct.CulinaryItemBaseMixin
[30May2022 19:34:28.374] [main/WARN] [mixin/]: Error loading class: org/jwaresoftware/mcmods/vfp/common/VfpPantryItem (java.lang.ClassNotFoundException: null)
[30May2022 19:34:28.375] [main/WARN] [mixin/]: @Mixin target org.jwaresoftware.mcmods.vfp.common.VfpPantryItem was not found origins.forge.mixins.json:compat.vfp.VfpPantryItemMixin
[30May2022 19:34:37.845] [main/FATAL] [mixin/]: Mixin apply failed pehkui.mixins.json:EnderCrystalEntityMixin -> net.minecraft.entity.item.EnderCrystalEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Specified index 4 for @ModifyArg is invalid for args (Lnet/minecraft/world/World;Lnet/minecraft/entity/Entity;DDDFLnet/minecraft/world/Explosion$Mode;), expected F on net/minecraft/entity/item/EnderCrystalEntity::onDamageCreateExplosionProxy [INJECT Applicator Phase -> pehkui.mixins.json:EnderCrystalEntityMixin -> Apply Injections ->  -> Inject -> pehkui.mixins.json:EnderCrystalEntityMixin->@ModifyArg::onDamageCreateExplosionProxy(F)F]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 4 for @ModifyArg is invalid for args (Lnet/minecraft/world/World;Lnet/minecraft/entity/Entity;DDDFLnet/minecraft/world/Explosion$Mode;), expected F on net/minecraft/entity/item/EnderCrystalEntity::onDamageCreateExplosionProxy [INJECT Applicator Phase -> pehkui.mixins.json:EnderCrystalEntityMixin -> Apply Injections ->  -> Inject -> pehkui.mixins.json:EnderCrystalEntityMixin->@ModifyArg::onDamageCreateExplosionProxy(F)F]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:158) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:113) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:103) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1355) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	at net.minecraft.entity.EntityType.<clinit>(EntityTypeMixin.java:166) ~[?:?]
	at net.minecraft.world.gen.feature.DungeonsFeature.<clinit>(DungeonsFeature.java:24) ~[?:?]
	at net.minecraft.world.gen.feature.Feature.<clinit>(Feature.java:37) ~[?:?]
	at net.minecraft.world.gen.feature.Features.<clinit>(SourceFile:92) ~[?:?]
	at net.minecraft.util.registry.WorldGenRegistries.func_243672_e(WorldGenRegistries.java:39) ~[?:?]
	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_312]
	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464) ~[?:?]
	at net.minecraft.util.registry.Bootstrap.func_151354_b(BootstrapMixin.java:38) ~[?:?]
	at net.minecraft.server.Main.main(MainMixin.java:92) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.26.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.26.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.26.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.26.jar:?]
	at io.izzel.arclight.common.ArclightMain.run(ArclightMain.java:50) [arclight-forge-1.16.5-1.0.24-SNAPSHOT.jar:arclight-1.16.5-1.0.24-SNAPSHOT-dabfea43]
	at io.izzel.arclight.server.Main_Forge.main(Main_Forge.java:16) [arclight-forge-1.16.5-1.0.24-SNAPSHOT.jar:arclight-1.16.5-1.0.24-SNAPSHOT-dabfea43]
	at io.izzel.arclight.server.Launcher.main(Launcher.java:16) [arclight-forge-1.16.5-1.0.24-SNAPSHOT.jar:arclight-1.16.5-1.0.24-SNAPSHOT-dabfea43]
[30May2022 19:34:37.852] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[30May2022 19:34:37.852] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[30May2022 19:34:37.853] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[30May2022 19:34:37.853] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[30May2022 19:34:37.853] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[30May2022 19:34:37.854] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[30May2022 19:34:37.854] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[30May2022 19:34:37.854] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[30May2022 19:34:37.854] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[30May2022 19:34:37.855] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: 	at io.izzel.arclight.common.ArclightMain.run(ArclightMain.java:50)
[30May2022 19:34:37.855] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: 	at io.izzel.arclight.server.Main_Forge.main(Main_Forge.java:16)
[30May2022 19:34:37.855] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:52]: 	at io.izzel.arclight.server.Launcher.main(Launcher.java:16)
[30May2022 19:34:37.855] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.reflect.InvocationTargetException
[30May2022 19:34:37.856] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[30May2022 19:34:37.856] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[30May2022 19:34:37.856] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[30May2022 19:34:37.856] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[30May2022 19:34:37.856] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[30May2022 19:34:37.857] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[30May2022 19:34:37.857] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	... 10 more
[30May2022 19:34:37.857] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[30May2022 19:34:37.857] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[30May2022 19:34:37.857] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[30May2022 19:34:37.858] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[30May2022 19:34:37.858] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[30May2022 19:34:37.858] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[30May2022 19:34:37.858] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[30May2022 19:34:37.858] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[30May2022 19:34:37.858] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[30May2022 19:34:37.859] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[30May2022 19:34:37.859] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[30May2022 19:34:37.859] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[30May2022 19:34:37.859] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.entity.EntityType.<clinit>(EntityTypeMixin.java:166)
[30May2022 19:34:37.859] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.world.gen.feature.DungeonsFeature.<clinit>(DungeonsFeature.java:24)
[30May2022 19:34:37.859] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.world.gen.feature.Feature.<clinit>(Feature.java:37)
[30May2022 19:34:37.860] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.world.gen.feature.Features.<clinit>(SourceFile:92)
[30May2022 19:34:37.860] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243672_e(WorldGenRegistries.java:39)
[30May2022 19:34:37.860] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[30May2022 19:34:37.860] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
[30May2022 19:34:37.860] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[30May2022 19:34:37.860] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[30May2022 19:34:37.861] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(BootstrapMixin.java:38)
[30May2022 19:34:37.861] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.server.Main.main(MainMixin.java:92)
[30May2022 19:34:37.861] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	... 16 more
[30May2022 19:34:37.861] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [pehkui.mixins.json:EnderCrystalEntityMixin] from phase [DEFAULT] in config [pehkui.mixins.json] FAILED during APPLY
[30May2022 19:34:37.861] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
[30May2022 19:34:37.862] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
[30May2022 19:34:37.862] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[30May2022 19:34:37.862] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	... 37 more
[30May2022 19:34:37.862] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 4 for @ModifyArg is invalid for args (Lnet/minecraft/world/World;Lnet/minecraft/entity/Entity;DDDFLnet/minecraft/world/Explosion$Mode;), expected F on net/minecraft/entity/item/EnderCrystalEntity::onDamageCreateExplosionProxy [INJECT Applicator Phase -> pehkui.mixins.json:EnderCrystalEntityMixin -> Apply Injections ->  -> Inject -> pehkui.mixins.json:EnderCrystalEntityMixin->@ModifyArg::onDamageCreateExplosionProxy(F)F]
[30May2022 19:34:37.862] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:158)
[30May2022 19:34:37.862] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:113)
[30May2022 19:34:37.863] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82)
[30May2022 19:34:37.863] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:103)
[30May2022 19:34:37.863] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
[30May2022 19:34:37.863] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
[30May2022 19:34:37.863] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1355)
[30May2022 19:34:37.863] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[30May2022 19:34:37.863] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[30May2022 19:34:37.864] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[30May2022 19:34:37.864] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[30May2022 19:34:37.864] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[30May2022 19:34:37.864] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[30May2022 19:34:37.864] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	... 37 more
[30May2022 19:34:37.864] [main/INFO] [STDERR/]: [io.izzel.arclight.common.ArclightMain:run:53]: Fail to launch Arclight.
:</summary>
<p>

**Comment by JustRed23** [comment]
[I fixed this on Magma 1.18.2.](https://git.magmafoundation.org/magmafoundation/Magma-1-18-x/-/merge_requests/27)

**Comment by Virtuoel** [comment]
Closing now that this is fixed on Magma.

**Comment by flemilwolf** [comment]
@Virtuoel  i understand, but it still doesn't work in arclight, this hybrid server api is a little different from mohist and magma servers, could you review, or let us know what it is so we can take the arlight dev to Izzel
