### ISSUE TITLE
[Bug]: eye height stopped working?

### ISSUE THREAD

**Issue by magnacrabb** [Virtuoel/Pehkui#461]
### Minecraft version(s)

1.20.1

### Mod loader

Forge

### Mod loader version

47.2.0/47.2.1

### In what kind of world or server did the problem occur?

A multiplayer server that I was connected to

### What went wrong? (Crash logs don't go here)

eye height randomly stopped displaying correctly at some point, acting as though it was set to 1 when it wasnt, but it goes back to the correct eye height when sneaking.
i tested it on an older copy of the modpack and it was still like that so it doesnt seem to be due to mod updates? 

### Full list of installed mods and their version numbers

YungsBetterDungeons-1.20-Forge-4.0.3.jar, additionalentityattributes-forge-1.4.0.5+1.20.1.jar, player-animation-lib-forge-1.0.2-rc1+1.20.jar, nether-s-exoticism-1.20.1-1.2.6.jar, stalwart-dungeons-1.20.1-1.2.8.jar, apoli-forge-1.20.1-2.9.0.2.jar, rubidium-mc1.20.1-0.7.1.jar, YungsApi-1.20-Forge-4.0.2.jar, bagus_lib-1.20.1-4.0.3.jar, Kambrik-6.1.1+1.20.1-forge.jar, balm-forge-1.20.1-7.1.4.jar, whatareyouvotingfor2023-1.20.1-1.2.2.jar, immersive_armors-1.6.1+1.20.1-forge.jar, JustEnoughResources-1.20.1-1.4.0.238.jar, YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar, cloth-config-11.1.106-forge.jar, soundphysics-forge-1.20.1-1.2.1.jar, supplementaries-1.20-2.6.15.jar, athena-forge-1.20.1-3.1.1.jar, structure_gel-1.20.1-2.15.0.jar, AdvancementPlaques-1.20.1-forge-1.4.10.jar, xaeros_waystones_compability-1.0.jar, repurposed_structures-7.1.7+1.20.1-forge.jar, BotanyTrees-Forge-1.20.1-9.0.7.jar, supermartijn642corelib-1.1.15-forge-mc1.20.jar, YungsBridges-1.20-Forge-4.0.3.jar, resourcefulconfig-forge-1.20.1-2.1.0.jar, portablemobs-1.2.0-forge-mc1.20.jar, curios-forge-5.3.5+1.20.1.jar, origins-forge-1.20.1-1.10.0.2-all.jar, Searchables-forge-1.20.1-1.0.2.jar, YungsExtras-1.20-Forge-4.0.3.jar, FramedBlocks-9.1.6.jar, cumulus_menus-1.20.1-1.0.0-beta.1-neoforge.jar, cfm-forge-1.20.1-7.0.0-pre36.jar, forge_golemfirststonemod-0.0.13-1.20.1.jar, flib-1.20.1-0.0.11.jar, YungsBetterEndIsland-1.20-Forge-2.0.4.jar, nitrogen_internals-1.20.1-0.1.3-neoforge.jar, l2library-2.4.20.jar, fps-shower 1.20.1.jar, YungsBetterMineshafts-1.20-Forge-4.0.4.jar, EnchantingInfuser-v8.0.2-1.20.1-Forge.jar, mcw-lights-1.0.6-mc1.20.1forge.jar, Essential (forge_1.20.1).jar, YungsBetterJungleTemples-1.20-Forge-2.0.4.jar, snifferent-1.0.3-1.20.1.jar, SmartBrainLib-forge-1.20.1-1.12.jar, elytraslot-forge-6.3.0+1.20.1.jar, puzzlesapi-forge-8.0.2.jar, l2tabs-0.1.5.jar, harvestwithease-1.20.1-7.0.0.2-forge.jar, jei-1.20.1-forge-15.2.0.27.jar, Block_Swapper-1.20.1-2.0a.jar, Pehkui-3.7.8+1.20.1-forge.jar, goblintraders-forge-1.20.1-1.9.3.jar, epicsamurai-0.0.27.1-1.20.1-forge.jar, caelus-forge-3.1.0+1.20.jar, realmrpg_fallen_adventurers_1.0.1_forge_1.20.1.jar, NaturesCompass-1.20.1-1.11.2-forge.jar, BotanyPots-Forge-1.20.1-13.0.17.jar, l2screentracker-0.1.3.jar, puzzlesaccessapi-forge-8.0.5.jar, extractinator-forge-1.20-2.2.0.jar, mcw-paths-1.0.3forge-mc1.20.1.jar, ironchest-1.20.1-14.4.4.jar, client-1.20.1-20230612.114412-srg.jar, TerraBlender-forge-1.20.1-3.0.0.169.jar, MouseTweaks-forge-mc1.20-2.25.jar, bettercombat-forge-1.7.4+1.20.1.jar, combatroll-forge-1.2.2+1.20.1.jar, moresnifferflowers-1.2.1.jar, spectrelib-forge-0.13.14+1.20.1.jar, CorgiLib-forge-1.20.1-4.0.0.4.jar, calio-forge-1.20.1-1.11.0.1.jar, betterfpsdist-1.20.1-3.9.jar, kffmod-4.5.0.jar, notenoughanimations-forge-1.6.4-mc1.20.jar, flywheel-forge-1.20.1-0.6.10-7.jar, Xaeros_Minimap_23.8.3_Forge_1.20.jar, Croptopia-1.20.1-FORGE-2.3.2.jar, baubley-heart-canisters-1.20.1-1.0.5.jar, polymorph-forge-0.49.0+1.20.1.jar, JustEnoughProfessions-forge-1.20.1-3.0.1.jar, earthmobsmod-1.20.1-9.0.1.jar, entityculling-forge-1.6.2-mc1.20.1.jar, canary-mc1.20.1-0.2.7.jar, moremobvariants-forge+1.20-1.2.2.jar, lootr-1.20-0.7.30.73.jar, occultism-1.20.1-1.88.1.jar, PuzzlesLib-v8.0.24-1.20.1-Forge.jar, denseores-1.20.1-1.2.1.jar, realmrpg_dragon_wyrms_0.9.0_forge_1.20.1.jar, cosmeticarmorreworked-1.20.1-v1a.jar, realmrpg_pots_and_mimics_1.0.2_forge_1.20.1.jar, grappling_hook_mod-1.20.1-1.20.1-v13.jar, CyclopsCore-1.20.1-1.18.12.jar, blue_skies-1.20.1-1.3.29.jar, YungsBetterWitchHuts-1.20-Forge-3.0.3.jar, geckolib-forge-1.20.1-4.2.3.jar, aether-1.20.1-1.0.0-beta.1.3-neoforge.jar, lost_aether_content-1.20.1-1.2.1.jar, ancient_aether-0.6.15.jar, deep_aether-1.20.1-1.0.10.jar, aeroblender-1.20.1-1.0.1-neoforge.jar, muffins-slimegolem-1.20.1-1.1.2-forge.jar, Galosphere-1.20.1-1.3.2-Forge.jar, YungsBetterOceanMonuments-1.20-Forge-3.0.3.jar, Tips-Forge-1.20.1-12.0.3.jar, dynamiclights-1.20.1.1.jar, sophisticatedcore-1.20.1-0.5.99.453.jar, gpumemleakfix-1.20.1-1.6.jar, XaerosWorldMap_1.35.0_Forge_1.20.jar, JRFTL-1.20.1-1.6.0.jar, cookingforblockheads-forge-1.20-16.0.1.jar, Controlling-forge-1.20.1-12.0.2.jar, citadel-2.4.5-1.20.1.jar, alexsmobs-1.22.6.jar, Rats-1.20.1-8.1.2.jar, forge-1.20.1-47.2.1-universal.jar, appleskin-forge-mc1.20.1-2.5.1.jar, mixinextras-forge-0.2.0-rc.5.jar, culinaryconstruct-forge-5.2.0+1.20.1.jar, Bookshelf-Forge-1.20.1-20.1.6.jar, sophisticatedbackpacks-1.20.1-3.18.65.935.jar, relics-1.20.1-0.4.9.jar, mcw-doors-1.1.0forge-mc1.20.1.jar, bygonenether-1.3.2-1.20.x.jar, dragonmounts-1.20.1-1.1.5.b3.jar, dummmmmmy-1.20-1.8.3.jar, l2damagetracker-0.1.5.jar, twilightforest-1.20.1-4.3.1860-universal.jar, EquipmentCompare-1.20.1-forge-1.3.7.jar, chipped-forge-1.20.1-3.0.1.jar, FarmersDelight-1.20.1-1.2.3.jar, ends_delight-1.20.1-1.0.1.jar, mcw-fences-1.0.7-mc1.20.1forge.jar, colorfulhearts-forge-1.20.1-4.0.3.jar, Sniffer+-forge-1.20.1-0.2.0.jar, SlotCycler-v8.0.1-1.20.1-Forge.jar, Bountiful-6.0.3+1.20.1-forge.jar, L_Enders_Cataclysm-1.39 -1.20.1.jar, Patchouli-1.20.1-81-FORGE.jar, basicweapons-forge-mc1.20.1+1.1.0.jar, BetterThirdPerson-Forge-1.20-1.9.0.jar, elevatorid-1.20.1-1.8.15.jar, ftb-ultimine-forge-2001.1.2.jar, YungsBetterStrongholds-1.20-Forge-4.0.3.jar, resourcefullib-forge-1.20.1-2.1.11.jar, twilightdelight-2.0.3.jar, deeperdarker-forge-1.20.1-1.2.1.jar, architectury-9.1.12-forge.jar, otyacraftengine-forge-mc1.20-3.7.0-alpha.2.jar, ftb-library-forge-2001.1.3.jar, cupboard-1.20.1-2.1.jar, productivebees-1.20.1-12.2.4.jar, The_Undergarden-1.20.1-0.8.8.jar, framework-forge-1.20.1-0.6.16.jar, PortableCraftingTable-1.20.1-3.2.2-[FORGE].jar, BetterAdvancements-1.20.1-0.3.2.161.jar, MobPlaques-v8.0.0-1.20.1-Forge.jar, octolib-0.1.jar, enlightend-5.0.9-1.20.1.jar, create-1.20.1-0.5.1.e.jar, waystones-forge-1.20-14.0.2.jar, Clumps-forge-1.20.1-12.0.0.3.jar, comforts-forge-6.3.4+1.20.1.jar, artifacts-forge-9.1.0.jar, SimpleStorageNetwork-1.20.1-1.10.0.jar, CustomPlayerModels-1.20-0.6.12a.jar, MagicDoorknob-1.20.1-1.0.0.687.jar, create-confectionery1.20.1_v1.0.9.jar, YungsBetterDesertTemples-1.20-Forge-3.0.3.jar, ExplorersCompass-1.20.1-1.3.3-forge.jar, netherdepthsupgrade-3.1.0-1.20.jar, extra_details-0.2+1.20-1.20.1-beta.jar, TravelersTitles-1.20-Forge-4.0.1.jar, tarotcards-1.20-1.5-release.jar, friendsandfoes-forge-mc1.20.1-1.9.7.jar, ColossalChests-1.20.1-1.8.4.jar, craftingtweaks-forge-1.20-18.2.1.jar, alexscaves-1.0.3.jar, simplyswords-forge-1.51.4-1.20.1.jar, moonlight-1.20-2.8.50-forge.jar, endermanoverhaul-forge-1.20.1-1.0.1.jar, eccentrictome-1.20.1-1.10.1.jar, Jade-1.20.1-forge-11.6.3.jar, nethersdelight-1.20.1-4.0.jar, modulargolems-2.4.17.jar, Iceberg-1.20.1-forge-1.1.15.jar, storagedrawers-1.20.1-12.0.2.jar, irons_spellbooks-1.20.1-2.0.1.jar, invhud.forge.1.20.1-3.4.18.jar, betterarcheology-1.0.2.jar, immersiveores-1.20.1-0.6.jar, modonomicon-1.20.1-forge-1.40.0.jar, creeperoverhaul-3.0.1-forge.jar, ferritecore-6.0.0-forge.jar, solcarrot-1.20.1-1.15.0.jar, Etcetera-1.20.1-1.1.3-Forge.jar, charmofundying-forge-6.4.2+1.20.1.jar, l2itemselector-0.1.5.jar, expandability-forge-9.0.0.jar, overloadedarmorbar-1.20.1-1.jar

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by magnacrabb** [comment]
update: as soon as i posted this, it fixed itself... but only for my friend (who hosts the server), but not for me?

**Comment by magnacrabb** [comment]
update 2: figured out where its from, it was from updating alex caves to 1.0.3

**Comment by Virtuoel** [comment]
This is now fixed in the latest version of Alex's Caves.

**Comment by terg-but-ius** [comment]
Hey, I'm still experiencing this issue (NeoForge, 47.1.79 I think?) even with having updated Alex's Caves. Here's the modlist:
![image](https://github.com/Virtuoel/Pehkui/assets/59403976/a0393222-e7f3-41e2-aa69-1d9def18f786)
