### ISSUE TITLE
[Bug]: Crashing while loading mods.

### ISSUE THREAD

**Issue by Beeper-Skeeper** [Virtuoel/Pehkui#470]
### Minecraft version(s)

1.16.5

### Minecraft version details

1.16.5

### Mod loader

Forge

### Mod loader version

Forge, curseforge version 36.2.39

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

The problem was that it crashes in the mod load start up when minecraft is launched, so unfortunately I can't provide any help on how to reproduce it besides installing the mod and trying to launch minecraft.

### Full list of installed mods and their version numbers

Ex:
Mod name
Author/creator

A Sylvan Origin [FORGE/FABRIC]
candycanecazoo
Adorn (Forge)
Juicebus
Adventures Structures
erixon_07
AI Improvements
QueenOfMissiles
Akashic Tome
Vazkii
Alex's Mobs
sbom_xela
AntiGhost
Giselbaer
Antique Atlas
Hunternif
AppleSkin
squeek502
Aquaculture 2
Shadow
Architectury API (Fabric/Forge)
shedaniel
Artifacts
ochotonida
AutoRegLib
Vazkii
Better Advancements
way2muchnoise
Better Barrels
mrpineapppl3
Better Biome Blend
FionaTheMortal
Better Compatibility Checker
Gaz_
Better Fps - Render Distance[Forge]
someaddon
BetterEnd Reforked
someoneelsewastaken
BetterF3
cominixo
BetterNether Reforged
someoneelsewastaken
BlockCarpentry
PianoManu
Bookshelf
DarkhaxDev
Bountiful (Forge)
Ejektaflex
Builders Dimension
thegartmans522
Caelus API (Forge)
TheIllusiveC4
CB: Compressed Blocks
sa_shiro
Chisel
tterrag1098
Chisels & Bits - For Forge
AlgorithmX2
Citadel
sbom_xela
Cloth Config API (Fabric/Forge)
shedaniel
Clumps
Jaredlll08
Collective
Serilum
ConnectedTexturesMod
tterrag1098
Controlling
Jaredlll08
Corpse
henkelmax
Cosmetic Armor Reworked
LainMI
CraftTweaker
Jaredlll08
Create
simibubi
Create Deco
talrey
Create Gears
kotakotik22
Create Goggles (Create Plus)
Robocraft999
Create Stuff & Additions
Furti_Two
Create: Alloyed
MythrilBagels
CreateTweaker
Jaredlll08
Cucumber Library
BlakeBr0
Curios API (Forge)
TheIllusiveC4
Custom Starter Gear
brandon3055
DataFixerSlayer (improves RAM usage)
Vazkii
Dimensional Dungeons
Catastrophe573
Double Slabs
CJMinecraft01
ExpandAbility
florensie
Extended Crafting
BlakeBr0
FancyMenu [Forge]
Keksuccino
Fast Furnace minus Replacement
tfarecnim
FastSuite
Shadows_of_Fire
FastWorkbench Minus Replacement
tfarecnim
FerriteCore (Forge)
malte0811
Flywheel
jozufozu
FTB Backups (Forge)
FTB
FTB Chunks (Forge)
FTB
FTB Essentials (Forge & Fabric)
FTB
FTB Library (Forge)
FTB
FTB Ranks (Forge)
FTB
FTB Structures (Forge)
FTB
FTB Teams (Forge)
FTB
GeckoLib
Gecko
Get It Together, Drops!
bl4ckscor3
Goblins & Dungeons
superlord_9362
Ice and Fire: Dragons
sbom_xela
Iceberg [Forge]
Grend_G
Inventory HUD+
dmitrylovin
JEITweaker
Jaredlll08
JourneyMap
techbrew
Just Enough Items (JEI)
mezz
KleeSlabs
BlayTheNinth
Konkrete [Forge]
Keksuccino
Kotlin for Forge
thedarkcolour
Ksyxis
VidTu
KubeJS
LatvianModder
Legendary Tooltips [Forge]
Grend_G
Macaw's Doors
sketch_macaw
Macaw's Fences and Walls
sketch_macaw
Macaw's Furniture
sketch_macaw
Macaw's Lights and Lamps
sketch_macaw
Macaw's Windows
sketch_macaw
Magnesium
someoneelsewastaken
Magnesium/Rubidium Dynamic Lights
Anthxny
Magnesium/Rubidium Extras
Anthxny
Mantle
mDiyo
Masonry
Shadow
Mo' Structures (Forge)
ffrannny
Moonlight Lib
MehVahdJukaar
More Create Stuffs
JerryLu086
Mouse Tweaks
YaLTeR
Mowzie's Mobs
bobmowzie
Neat
Vazkii
Netherite Plus Mod
OroArmor
No Recipe Advancements
MutantGumdrop
Oh The Biomes You'll Go
AOCAWOL
Origins (Forge)
EdwinMindcraft
Out Of Sight
Corosus
Overworld Two (Forge)
Corgi_Taco
Pam's HarvestCraft 2 - Crops
pamharvestcraft
Pam's HarvestCraft 2 - Food Core
pamharvestcraft
Pam's HarvestCraft 2 - Food Extended
pamharvestcraft
Pam's HarvestCraft 2 - Trees
pamharvestcraft
Patchouli
Vazkii
Path Under Gates
cyberslas
Pehkui
Virtuoel
Performant
someaddon
Piglin Brute
TheImperiumCentral
Placebo
Shadows_of_Fire
Polymorph (Fabric/Forge/Quilt)
TheIllusiveC4
Prism [Forge]
Grend_G
RandomPatches (Forge)
TheRandomLabs
RecipeBuffers
malte0811
Repurposed Structures (Forge)
telepathicgrunt
Rhino
LatvianModder
Rubidium
Asek3
Server Tab Info
black_dog20
Shrines Structures
silverminer007
Simple Storage Network
Lothrazar
Simply Origins (Forge/Fabric)
SimplyKamu
Soaring Structures 2 - Forge / Fabric
STGMC
Spawner Bug Fix
MacTso
Structures Plus II
Qra5
Sulfuric
someoneelsewastaken
Supplementaries
MehVahdJukaar
TiCBC - Tinkers Better Compat
ianm1647
Tinkers Construct
mDiyo
Tips
DarkhaxDev
Toast Control
Shadows_of_Fire
Torch Slabs Mod
EndlesNights
Torchmaster
xalcon
Traveler's Backpack
Tiviacz1337
Valhelsia Core
ValhelsiaTeam
Valhelsia Structures
ValhelsiaTeam
Vein Mining (Fabric/Forge/Quilt)
TheIllusiveC4
Waystones
BlayTheNinth
WorldEdit
sk89q
XL Packets
tfarecnim
YUNG's API (Forge)
YUNGNICKYOUNG
YUNG's Better Caves (Forge)
YUNGNICKYOUNG
YUNG's Better Dungeons (Forge)
YUNGNICKYOUNG
YUNG

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
I know it said to copy and paste a crash report, but the only thing the launcher bothered giving me, was an error code: 1. That's it, I don't know what else I would put here.

**Comment by Beeper-Skeeper** [comment]
I should mention that it also crashes just by itself on the same versions for minecraft and curseforge, as well as outputting the same exit code number.

**Comment by Virtuoel** [comment]
Should now be resolved as of the 3.8.0 release.

If you still have crash issues with this latest release, please be sure to include the crash report from the `crash-reports` folder in your `.minecraft` folder.

**Comment by Beeper-Skeeper** [comment]
> Should now be resolved as of the 3.8.0 release.
> 
> If you still have crash issues with this latest release, please be sure to include the crash report from the `crash-reports` folder in your `.minecraft` folder.

Unfortunately it still crashes, and still gives me the same reply of "Exit code: 1"

**Comment by Beeper-Skeeper** [comment]
Came back here to say that it finally works now. Thanks.
